l_english:

 MR_MUSICAL_TRADITION_RANKING_BUTTON: "M. Tradition"
 MR_RANKING_BY_MUSICAL_TRADITION: "Show Ranking by [concept_elgar_musical_tradition]"
 MR_COMPOSER_RANKING_BUTTON: "Composers"
 MR_RANKING_BY_COMPOSER: "Show Ranking of all the [Concept('concept_elgar_composer','$concept_elgar_composers$')] in the world."
 COMPOSER_COMPOSER_RANKING_HEADER: "#V [Concept('concept_elgar_composer','$concept_elgar_composers$')] of the World ranked by [concept_artists_experience]"