l_korean:
 MR_MUSICAL_TRADITION_RANKING_BUTTON: "M. 전통"
 MR_RANKING_BY_MUSICAL_TRADITION: "[concept_elgar_musical_tradition]별 순위 표시"
 MR_COMPOSER_RANKING_BUTTON: "작곡가들"
 MR_RANKING_BY_COMPOSER: "전 세계의 모든 [Concept('concept_elgar_composer','$concept_elgar_composers$')]의 순위를 표시합니다."
 COMPOSER_COMPOSER_RANKING_HEADER: "#V 전 세계 [Concept('concept_elgar_composer','$concept_elgar_composers$')]를 [concept_artists_experience] 기준으로 순위 매김"