l_simp_chinese:

 MR_COMPOSER_ACHIEVEMENTS_TT: "[AddLocalizationIf( Scope.IsSet , 'elgar_composer_achievements_loc')][AddLocalizationIf( Not(Scope.IsSet) , 'elgar_composer_achievements_no_composer_loc')]" #deepl:768039705

 elgar_composer_achievements_loc: "$elgar_composer_achievements_intro_loc$[Scope.GetCharacter.GetCustom('elgar_composer_achievement_is_composer_virtuoso_type')][Scope.GetCharacter.GetCustom('elgar_composer_achievement_is_composer_conductor_type')]" #deepl:1401532535
 elgar_composer_achievements_no_composer_loc: "#V  [concept_elgar_composer] #! 的成就，一旦您有了成就，就会显示在这里。" #deepl:238214084
 elgar_composer_achievements_intro_loc: "#V 这位作曲家的成就#! （[Scope.GetCharacter.GetFullName] ）是一位享誉[Scope.Var('elgar_composer_experience').GetValue|V0] 的作曲家。迄今为止，[Scope.GetCharacter.GetSheHe] ，曾在[Scope.Var('elgar_composer_num_tours_var').GetValue|V0] 巡回演出。在[Scope.GetCharacter.GetHerHis] 的众多作品中，[Scope.Var('elgar_composer_num_compositions_var').GetValue|V0] 尤为突出。" #deepl:784174613

 elgar_composer_achievement_is_composer_virtuoso_loc: "\[Scope.GetCharacter.GetSheHe|U] 是一个优秀的#V Virtuoso#! 。" #deepl:247745204
 elgar_composer_achievement_is_composer_conductor_loc: "\[Scope.GetCharacter.GetSheHe|U] 被认为是著名的#V 指挥#! 。" #deepl:1668837524
