l_simp_chinese:
 MR_MUSICAL_TRADITION_RANKING_BUTTON: "音乐传统"
 MR_RANKING_BY_MUSICAL_TRADITION: "按[concept_elgar_musical_tradition]显示排名"
 MR_COMPOSER_RANKING_BUTTON: "作曲家"
 MR_RANKING_BY_COMPOSER: "显示全球所有[Concept('concept_elgar_composer','$concept_elgar_composers$')]的排名。"
 COMPOSER_COMPOSER_RANKING_HEADER: "#V 依据[Concept('concept_elgar_composer','$concept_elgar_composers$')][concept_artists_experience]的世界排名"